# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c87459fa42b15f49f150f1c9884b96ba1c38906619050d99e3345381e369e458543ab18ac32ff0fae79433e4dcc58e24e9b22cf577daa239693c00942cfb6d

test:
  secret_key_base: 16240972aee315380c52dfefd6c98433579b18c3fb8445736c4a11ded8b6ffaed2475b8a75452d42926e81ee6f1a510dc67b1a060da3b2f5897a3aff91b17448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
